version: '3.7'
services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'

  prometheus:
    image: 'prom/prometheus:v2.30.1'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
